const grid=document.querySelector('#product-grid'),empty=document.querySelector('#empty'),search=document.querySelector('#search-input');
let category='all', cart=JSON.parse(localStorage.getItem('dabom-cart')||'[]');
const won=n=>n?`${n.toLocaleString('ko-KR')}원`:'가격 문의';
function render(){const q=search.value.trim().toLowerCase();const list=PRODUCTS.filter(p=>(category==='all'||p.category===category)&&p.name.toLowerCase().includes(q));grid.innerHTML=list.map((p,i)=>`<article class="product-card"><a class="product-image" href="http://www.dabomsecurity.com/goods/goods_view.php?goodsNo=${p.id}" target="_blank" rel="noopener"><img src="${p.image}" alt="${p.name}" loading="lazy"><span>${i<4?'BEST':'DABOM'}</span></a><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><div><strong class="${p.price?'':'ask'}">${won(p.price)}</strong><button class="add" data-id="${p.id}" aria-label="장바구니 담기">＋</button></div></div></article>`).join('');empty.hidden=!!list.length}
function setCategory(v){category=v;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===v));render();document.querySelector('#products').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));document.querySelector('#search-form').addEventListener('submit',e=>{e.preventDefault();category='all';render();document.querySelector('#products').scrollIntoView({behavior:'smooth'})});search.addEventListener('input',render);
function saveCart(){localStorage.setItem('dabom-cart',JSON.stringify(cart));document.querySelector('#cart-count').textContent=cart.length;const items=document.querySelector('#cart-items');items.innerHTML=cart.length?cart.map((id,i)=>{const p=PRODUCTS.find(x=>x.id===id);return `<article><img src="${p.image}" alt=""><div><small>${p.category}</small><b>${p.name}</b><strong>${won(p.price)}</strong></div><button data-remove="${i}">×</button></article>`}).join(''):'<p class="cart-empty">장바구니가 비어 있습니다.</p>';const total=cart.reduce((s,id)=>s+(PRODUCTS.find(p=>p.id===id)?.price||0),0);document.querySelector('#cart-total').textContent=won(total)}
grid.addEventListener('click',e=>{const b=e.target.closest('.add');if(!b)return;cart.push(b.dataset.id);saveCart();const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)});document.querySelector('#cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){cart.splice(+b.dataset.remove,1);saveCart()}});
const drawer=document.querySelector('#cart-drawer'),backdrop=document.querySelector('#drawer-backdrop');function toggleCart(on){drawer.classList.toggle('open',on);backdrop.classList.toggle('open',on);document.body.classList.toggle('locked',on)}document.querySelector('#cart-open').onclick=()=>toggleCart(true);document.querySelector('#cart-close').onclick=()=>toggleCart(false);backdrop.onclick=()=>toggleCart(false);document.querySelector('#checkout').onclick=()=>location.href='tel:051-532-0135';
document.querySelector('.menu-btn').onclick=()=>document.querySelector('.nav').classList.toggle('mobile-open');saveCart();render();
